# Generated by Django 2.2 on 2020-04-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Full Name.', max_length=60, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone No.', max_length=16, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email Address', max_length=254, null=True)),
                ('message', models.TextField(blank=True, help_text='Your Message.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Email Address', max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestDemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Full Name.', max_length=60, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone No.', max_length=16, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email Address', max_length=254, null=True)),
                ('message', models.TextField(blank=True, help_text='Your Message.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('enquiry_type', models.IntegerField(choices=[(1, 'WEB AND PORTAL DEVELOPMENT'), (2, 'DIGITAL AND SOCIAL MARKETING'), (3, 'ECOMMERCE STORES'), (4, 'MOBILE APPLICATION DEVELOPMENT'), (5, 'CONSULTING'), (6, 'ELEARNING'), (7, 'VIRTUAL CTO SERVICES'), (8, 'STARTUP MENTORING'), (9, 'SOFTWARE DEVELOPMENT')], default=1, help_text='Select a PORTAL Type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
