# Generated by Django 2.2 on 2020-04-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='give it a name.', max_length=60, null=True)),
                ('image', models.ImageField(blank=True, help_text='Image for the title.', null=True, upload_to='')),
                ('description', models.TextField(blank=True, help_text='Description for title.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='give it a name.', max_length=60, null=True)),
                ('image', models.ImageField(blank=True, help_text='Image for the title.', null=True, upload_to='')),
                ('description', models.TextField(blank=True, help_text='Description for title.', null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='pages.Service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
